### ISSUE TITLE
Feature 1: User can search for movies by titles

### ISSUE THREAD

**Issue by loganlee-lth** [loganlee-lth/Moogle#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for movies by their original, translated and alternative titles.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will enter a movie title into the search bar. The search query will be sent to the movie database API, and the API will respond with a list of movies that match the search criteria. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Pasted image 20230618161820](https://github.com/loganlee-lth/Moogle/assets/36302145/83205e63-7c1b-49c3-8fba-7a4a3a463f69)
![Pasted image 20230618161831](https://github.com/loganlee-lth/Moogle/assets/36302145/76d3ac91-92d2-43e8-aead-4479491a9e28)
![Pasted image 20230618161841](https://github.com/loganlee-lth/Moogle/assets/36302145/8145b1ed-6998-46a0-82df-1e1765902c73)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the `<header>` so that it matches the figma example.
- [x] Create the `data-view="search-view"` element which contains the search bar and the movie posters. 
- [x] Below the header, create the HTML for the search bar and the search button.
- [x] Create a dummy search result and style them to match the figma example.
- [x] Make the header positioned sticky.
- [x] Complete the HTML using the appropriate responsive layout classes.
  - [x] Write CSS for mobile devices first.
  - [x] Adjust styling to fluidly adapt to desktop.
- [x] Define a function that sends a search query to the movie database API which will fetch a list of movies that match the search criteria.
- [x] In `main.js`, define a function named `renderMovie` with a single parameter named `results`. This parameter represents an array of results from an API request. The function should generate and return a DOM tree for each movie from the array.
- [x] In `main.js`, add a `click` event listener to the button that:
   - [x] trims any leading or trailing whitespace from the search input and checks if the trimmed input is an empty string.
   - [x] makes an API request with the input to search for movies by title 
   - [x] retrieves and displays the search results 
   - [x] clear the search input field
   - [x] scroll the window back to the top
- [x] Remove the dummy search result once the search results are successfully being displayed. 
- [x] Add placeholder image for movies with no poster
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
