### ISSUE TITLE
Feature 2: User can add movies to their watchlist

### ISSUE THREAD

**Issue by loganlee-lth** [loganlee-lth/Moogle#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add movies to their watchlist.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After searching for movies by titles, user can add movies to their watchlist by interacting with the bookmark icon located on top of each movie poster.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Pasted image 20230620030616](https://github.com/loganlee-lth/Moogle/assets/36302145/26ee5b01-59f9-46a8-9890-b68c38943d6a)
![Pasted image 20230620030751](https://github.com/loganlee-lth/Moogle/assets/36302145/c2a9ff56-0ceb-4e86-9ccc-370ca145938a)
![Pasted image 20230620030311](https://github.com/loganlee-lth/Moogle/assets/36302145/1135eb95-1788-4532-b095-b70f5bf4ce8c)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a 'click' event listener to the `movie-results` container element which does the following when a movie's bookmark icon is clicked:
  - [x] stores the movie's information in a new object.
  - [x] assigns a movieID property to the new object, taken from the nextMovieId property of the data model.
  - [x] increments the nextMovieId property of the data model so that if another movie is bookmarked later, it will receive a different movieId.
  - [x] adds the new object the beginning of the data model's array of entries.
  - [x] changes the icon color.
- [x] In data.js, add a 'beforeunload' event listener to the window object that serializes the data model as JSON and stores the JSON in localStorage.
- [x] At the bottom of data.js, include a conditional statement that:
  - [x] checks to see if there is a JSON data model stored in localStorage.
  - [x] if there is, parse it and assign it to the initial data variable so that the user can continue adding entries to the pre-existing data model.
- [x] Update the `renderMovie` function to check if the movie is already bookmarked and add icon classes accordingly.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
