### ISSUE TITLE
Feature 3: User can view their watchlist

### ISSUE THREAD

**Issue by loganlee-lth** [loganlee-lth/Moogle#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their watchlist.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click on the watchlist located in the header section to see the movies they have bookmarked.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Pasted image 20230620030252](https://github.com/loganlee-lth/Moogle/assets/36302145/6c20b52b-fe30-4952-825a-0c9de247c3fa)
![Pasted image 20230620030311](https://github.com/loganlee-lth/Moogle/assets/36302145/0ad77925-176b-44a6-bb91-d9b2242ae4be)
![Pasted image 20230620030321](https://github.com/loganlee-lth/Moogle/assets/36302145/2bdf1c8f-b31e-45ab-bc64-15d4712d1e96)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the data-view="watchlist-view" element which contains the empty watchlist message and the watchlist container.
- [x] Create an event listener on the document which listens for the DOMContentLoaded event. In the callback function for that event, loop through the data.watchlist array and generate a DOM tree for each movie in the array, and append that DOM tree to the watchlist container.
- [x] Create a function named toggleNoMovies which toggles the empty watchlist text to show or hide when the function is called.
- [x] Create a new function named viewSwap with a single parameter representing the name of the view to show. This function should show the view whose name was provided as an argument.
- [x] Create an event handler function that utilizes the viewSwap function to show the proper view.
- [x] Update the `movie-results` eventlistener to prepend the new DOM tree to the watchlist container.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
