### ISSUE TITLE
Feature 4: User can delete movies from their watchlist

### ISSUE THREAD

**Issue by loganlee-lth** [loganlee-lth/Moogle#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete movies from their watchlist.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In the watchlist page, user will click on the bookmark icon of a particular movie to delete it from the watchlist. User will be given a confirmation dialog to prevent user errors.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Pasted image 20230622120651](https://github.com/loganlee-lth/Moogle/assets/36302145/871356dc-cb14-43be-bd8e-cd7a3f01a160)
![Pasted image 20230622120703](https://github.com/loganlee-lth/Moogle/assets/36302145/1a4b2c93-3b86-4664-9e96-cab75cab6bdc)
![Pasted image 20230622120709](https://github.com/loganlee-lth/Moogle/assets/36302145/a1a21171-3142-4874-a377-b618e3376708)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add an event listener to the `movie-watchlist` container in the watchlist view which does the following when the bookmark icon is clicked:
  - [x] finds the movie object in the data.watchlist array whose id matches the id attribute value of the clicked movie and assigns that movie's object to the data.clickedMovie property.
  - [x] removes `sticky` class from the `header` element.
  - [x] removes `hide` class from the `modal` element.
- [x] Add an event listener to the 'cancel' button on the modal that hides the modal when clicked.
- [x] Add an event listener to the 'delete' button on the modal that does the following when clicked:
  - [x] removes the corresponding movie object from the data model's watchlist array.
  - [x] removes the movie element from the DOM.
  - [x] conditionally uses the toggleEmptyWatchlist function to show the no movies text if needed.
  - [x] hides the modal.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
